name = "Lead and Leylines"
author = "TinorNoah"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "651ed829671f7f14a657363aee5a689e1810ca01fa56bc0e23413c670833b897"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
