name = "Lead and Leylines"
author = "TinorNoah"
version = "0.1.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4415dbdf8892d82bd6f5a4ecb52350704e7ed274ce12a4801d6effac2892877"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
