name = "Lead and Leylines"
author = "TinorNoah"
version = "0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18311ae0a42da7a72af31c9ef18733d7a7a25e82d8d78a69f8cab91255160a8a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
